ServerEvents.recipes(r=>{
r.remove({output:'constructionwand:core_destruction'})
r.shapeless(Item.of('minecraft:red_mushroom',2),
['#minecraft:logs','minecraft:shears','minecraft:sugar']
).damageIngredient({item:'minecraft:shears'},2)
r.shapeless(Item.of('minecraft:brown_mushroom',2),
['minecraft:mud','minecraft:shears','minecraft:sugar']
).damageIngredient({item:'minecraft:shears'},2)
r.shaped('twilightforest:deer_spawn_egg',[
    "aba",
    "bcb",
    "aba"
],{
    'a':'twilightforest:raw_venison',
    'b':'minecraft:bone',
    'c':'minecraft:ghast_tear'
})
r.shapeless('xkdeco:mechanical_item_display',
[
   'xkdeco:plain_item_display', 'create:brass_casing'
])
r.shapeless('xkdeco:gorgeous_item_display',[
    'xkdeco:plain_item_display','minecraft:red_carpet','minecraft:dark_oak_log'
    ])
r.shapeless('xkdeco:gorgeous_block_display',[
    'xkdeco:plain_block_display','minecraft:red_carpet','minecraft:dark_oak_log'
])
r.shapeless('xkdeco:mechanical_block_display',[
    'create:brass_casing','xkdeco:plain_block_display'
])
})
