ServerEvents.recipes(e => {
  e.remove({type:'lightmanscurrency:coin_mint'})
  e.remove({output:'lightmanscurrency:trading_core'})
  e.shaped('lightmanscurrency:trading_core',[
    'xxx',
    'xzx',
    'xxx'
  ],{
    'x':'lightmanscurrency:coin_copper',
    'z':'minecraft:quartz'
  })
  e.recipes.create.compacting(['lightmanscurrency:coin_chocolate_iron',
    'lightmanscurrency:coin_iron'],['lightmanscurrency:coin_iron',
      'create:bar_of_chocolate'])
  e.recipes.create.compacting(['lightmanscurrency:coin_chocolate_gold',
    'lightmanscurrency:coin_gold'],['lightmanscurrency:coin_gold',
      'create:bar_of_chocolate'])
  e.recipes.create.compacting(['lightmanscurrency:coin_chocolate_emerald',
    'lightmanscurrency:coin_emerald'],['lightmanscurrency:coin_emerald',
      'create:bar_of_chocolate'])
  e.recipes.create.compacting(['lightmanscurrency:coin_chocolate_diamond',
    'lightmanscurrency:coin_diamond'],['lightmanscurrency:coin_diamond',
      'create:bar_of_chocolate'])
  e.recipes.create.compacting(['lightmanscurrency:coin_chocolate_netherite',
    'lightmanscurrency:coin_netherite'],['lightmanscurrency:coin_netherite',
      'create:bar_of_chocolate'])
})
